alias c="clear"
alias e="exit"
alias clean="sudo apt autoremove"
alias update="sudo apt update && sudo apt upgrade"
alias v="nvim"
alias lg="lazygit"
alias ss="shutdown now"
alias bb="source ~/.bashrc"
alias searchup="sudo docker-compose -f /usr/local/searxng-docker/docker-compose.yaml up -d"
alias searchdown="sudo docker-compose -f /usr/local/searxng-docker/docker-compose.yaml down"

