# Bind prefix key to Ctrl a
set-option -g prefix C-a

# terminal color
set -g default-terminal "screen-256color"

set -g repeat-time 1000

# Catpuccin theme conf
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_status_modules_right "application session user host date_time"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"

# Bind r to reload
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded ~/.config/tmux/tmux.conf"

# Window number renaming
set -g base-index 1
set-window-option -g automatic-rename on

# Remap window split
bind | split-window -h
bind - split-window -v

# Vim-like keybindings for pane resizing in tmux
bind-key -r -T prefix       k              resize-pane -U 5
bind-key -r -T prefix       j              resize-pane -D 5
bind-key -r -T prefix       h              resize-pane -L 5
bind-key -r -T prefix       l              resize-pane -R 5
bind-key -r -T prefix       Ctrl-k         resize-pane -U
bind-key -r -T prefix       Ctrl-j         resize-pane -D
bind-key -r -T prefix       Ctrl-h         resize-pane -L
bind-key -r -T prefix       Ctrl-l         resize-pane -R


# Toggle statusline
bind b set-option -g status \; refresh-client -S


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
