#!/bin/bash

# Function to handle cleanup on exit
cleanup() {
    echo "Exiting..."
    exit 0
}

# Trap Ctrl+C (SIGINT) signal to call cleanup
trap cleanup SIGINT

# Check if a file path is provided
if [ -z "$1" ]; then
    echo "Usage: yt <file_name>"
    exit 1
fi

file_name="$1"

# File Path
file_path="/home/al/Music/links/$file_name"
echo "file_path: $file_path"

# Check if the file exists
if [ ! -f "$file_path" ]; then
    echo "Error: File not found!"
    exit 1
fi

# Read all lines from the file into an array
mapfile -t links < "$file_path"

# Shuffle the links
shuffled_links=($(shuf -e "${links[@]}"))

# Play each shuffled link in mpv
for link in "${shuffled_links[@]}"; do
    if [ -n "$link" ]; then
        echo "Playing: $link"
        mpv "$link"
    fi
done
